SELECT '/home/grep/src/' || RESULT.BOARD_ID || '/' || RESULT.FILE_ID || RESULT.FILE_NAME || RESULT.FILE_EXT AS FILE_PATH
FROM USED_GOODS_FILE RESULT
WHERE RESULT.BOARD_ID IN (
    SELECT COMPARISON.BOARD_ID 
    FROM USED_GOODS_BOARD COMPARISON
    WHERE COMPARISON.VIEWS = (
        SELECT MAX(VIEWS) FROM USED_GOODS_BOARD
    )
)
ORDER BY RESULT.FILE_ID DESC
